# Generated by Django 5.2 on 2025-04-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('payslip_file', models.FileField(blank=True, null=True, upload_to='uploads/payslips/')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='uploads/contracts/')),
                ('bank_statement_file', models.FileField(blank=True, null=True, upload_to='uploads/bank_statements/')),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='uploads/id_proofs/')),
                ('p60_file', models.FileField(blank=True, null=True, upload_to='uploads/p60_forms/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
