# Generated by Django 5.2 on 2025-04-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_customerdocumentupload_delete_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(max_length=100)),
                ('extracted_fields', models.JSONField(blank=True, null=True)),
                ('confidence_scores', models.JSONField(blank=True, null=True)),
                ('missing_fields', models.JSONField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.customerdocumentupload')),
            ],
        ),
    ]
